---
- name: Configuration of master node
  hosts: master_setup_host
  become: true
  tasks:
    - name: Hard Reset Kubernetes
      ansible.builtin.command: kubeadm reset -f
      failed_when: false

    - name: Clean up leftover networking and manifests
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cni/net.d
        - /var/lib/etcd
        - /etc/kubernetes/manifests

    - name: Force Containerd to use Systemd Cgroup
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      notify: Restart containerd

    - name: Restart containerd immediately
      ansible.builtin.meta: flush_handlers

    - name: Initialize K8S cluster
      ansible.builtin.command: >
        kubeadm init 
        --pod-network-cidr=172.16.0.0/16 
        --apiserver-advertise-address=192.168.100.5
        --ignore-preflight-errors=Mem
      register: kubeadm_init

    - name: Setup kubeconfig for zultahir
      ansible.builtin.shell: |
        mkdir -p /home/zultahir/.kube
        cp -i /etc/kubernetes/admin.conf /home/zultahir/.kube/config
        chown zultahir:zultahir /home/zultahir/.kube/config

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: yes
