---
- name: Manage Windows Local Users
  hosts: all
  gather_facts: no

  tasks:
    - name: Create a new local user
      ansible.windows.win_user:
        name: "JohnDoe"
        password: "ComplexPassword2026!"
        state: present
        groups:
          - Users
          - Remote Management Users
        groups_action: add  # Ensures user is added to these groups without removing existing ones
        password_never_expires: yes
        update_password: always # Only sets the password if the user is new
