- name: Install Apache on Group
  hosts: web_servers_apache  # This matches the Group Name you just made
  become: yes
  tasks:
    - name: Ensure apache is installed
      apt:
        name: apache2
        state: present
