---
- name: Reset Password and Enable RDP
  hosts: all
  gather_facts: no

  tasks:
    - name: Reset password and add to RDP group
      ansible.windows.win_user:
        name: "JohnDoe"
        password: "NewSecurePassword2026!"
        state: present
        update_password: always
        password_never_expires: yes
        password_expired: no
        groups:
          - Remote Desktop Users      # <--- Grants RDP access
          - Remote Management Users   # <--- Grants WinRM/Ansible access
        groups_action: add            # Adds to these groups without removing others
