---
- name: Update Windows Servers
  hosts: Group_Windows_2016
  vars:
    ansible_winrm_operation_timeout_sec: 300
    ansible_winrm_read_timeout_sec: 350
  tasks:
    - name: Install updates (Async)
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
        # Disable automatic reboot to allow async to work
        reboot: no
      async: 7200
      poll: 30
      register: update_result

    - name: Reboot if updates required it
      ansible.windows.win_reboot:
        reboot_timeout: 3600
      when: update_result.reboot_required
