---
- name: Join Worker Nodes to Cluster
  hosts: all
  become: true
  tasks:
    - name: Complete Worker Cleanup
      ansible.builtin.shell: |
        kubeadm reset -f
        systemctl stop kubelet
        systemctl stop containerd
        rm -rf /etc/cni/net.d /var/lib/kubelet/* /etc/kubernetes/*
        modprobe br_netfilter
        sysctl -w net.ipv4.ip_forward=1
      failed_when: false

    - name: Refresh Containerd Config
      ansible.builtin.shell: |
        rm -f /etc/containerd/config.toml
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
      notify: Restart containerd

    - name: Flush Handlers
      ansible.builtin.meta: flush_handlers

    - name: Wait for Runtime to settle
      ansible.builtin.pause:
        seconds: 10

    - name: Join Cluster with New Token
      ansible.builtin.command: >
        kubeadm join 192.168.0.102:6443 
        --token h8c8zu.nqy9ok2r399t2udn 
        --discovery-token-ca-cert-hash sha256:6bf6df19694e693e733a3014f8515537e625e1df44262447a8fa80af3f366bf6
        --v=5
      register: join_out

    - name: Debug Join Output
      ansible.builtin.debug:
        var: join_out.stdout_lines

  handlers:
    - name: Restart containerd
      ansible.builtin.systemd:
        name: containerd
        state: restarted
